name: Release
description: |
  Triggers on: 
    push to main-> validate
    pull_request closed-> publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  prerelease:
    name: Pre-Release Checks
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checking Out Repo
        uses: actions/checkout@v4

      - name: ğŸ”§ Setting Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org/"

      - name: ğŸ“¥ Installing pnpm
        run: npm install -g pnpm@10.10.0

      - name: ğŸ“¥ Installing Dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ”¨ Building Packages
        run: pnpm -r build

      - name: ğŸ•µï¸ Validating Dependencies
        run: pnpm cruise:validate

      - name: ğŸ§¹ Formatting
        run: pnpm prettier --check .

      - name: ğŸ§¹ Lint packages
        run: pnpm eslint .

      - name: ğŸ§ª Running Tests
        run: pnpm test

      - name: ğŸ“ Creating Version PR (Changesets)
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish
    if:
      github.event_name == 'pull_request' && github.event.pull_request.merged ==
      true
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checking Out Repo
        uses: actions/checkout@v4

      - name: ğŸ”§ Setting Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org/"

      - name: ğŸ“¥ Installing pnpm
        run: npm install -g pnpm@10.10.0

      - name: ğŸ“¦ Installing Dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ”¨ Building Packages
        run: pnpm -r build

      - name: ğŸ§­ Generating Dependency Graph
        run: pnpm cruise:generate

      - name: ğŸ§ª Generating Coverage Report
        run: pnpm coverage:generate

      - name: ğŸš€ Publishing to NPMJS
        run: pnpm changeset publish --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
