name: Release
description: |
  1. Push to main -> runs tests + may create Version PR
  2. Merge of Version PR to main -> publishes packages

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  prerelease:
    name: Pre-Release
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      has_changeset: ${{ steps.check_changeset.outputs.has_changeset }}
    steps:
      - name: â¬‡ï¸ Checking Out Repo
        uses: actions/checkout@v4

      - name: ğŸ”§ Setting Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org/"

      - name: ğŸ“¥ Installing pnpm
        run: npm install -g pnpm@10.10.0

      - name: ğŸ“¥ Installing Dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ”¨ Building Packages
        run: pnpm -r build

      - name: ğŸ•µï¸ Validating Dependencies
        run: pnpm cruise:validate

      - name: ğŸ§¹ Formatting
        run: pnpm prettier --check .

      - name: ğŸ§¹ Lint packages
        run: pnpm eslint .

      - name: ğŸ§ª Running Tests
        run: pnpm test

      - name: ğŸ“ Creating Version PR (Changesets)
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ§ Checking for Changeset Files
        id: check_changeset
        run: |
          if [ -n "$(ls .changeset/*.md 2>/dev/null)" ]; then
            echo "Changeset file found"
            echo "has_changeset=true" >> $GITHUB_OUTPUT
          else
            echo "No changeset file found"
            echo "has_changeset=false" >> $GITHUB_OUTPUT
          fi

  publish:
    name: Publish
    if:
      ${{ needs.prerelease.outputs.has_changeset == 'true' && github.event_name
      == 'pull_request' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    needs: prerelease

    steps:
      - name: â¬‡ï¸ Checking Out Repo
        uses: actions/checkout@v4

      - name: ğŸ”§ Setting Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org/"

      - name: ğŸ“¥ Installing pnpm
        run: npm install -g pnpm@10.10.0

      - name: ğŸ“¦ Installing Dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ”¨ Building Packages
        run: pnpm -r build

      - name: ğŸš€ Publishing to NPMJS
        run: pnpm changeset publish --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
