name: Release
description: |
  Triggers on: 
    push to main-> validate
    pull_request closed-> publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  validate:
    name: Validate Build & Test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: 拘勇 Checkout repo
        uses: actions/checkout@v4

      - name: 游댢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org/"

      - name: 游닌 Install pnpm
        run: npm install -g pnpm@10.10.0

      - name: 游닌 Install tsx
        run: pnpm add -g tsx

      - name: 游닍 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 游댣 Build packages
        run: pnpm -r build

      - name: 游빍 Test
        run: pnpm test

      - name: 游닇 Create Version PR (Changesets)
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish
    if:
      github.event_name == 'pull_request' && github.event.pull_request.merged ==
      true
    runs-on: ubuntu-latest

    steps:
      - name: 拘勇 Checkout repo
        uses: actions/checkout@v4

      - name: 游댢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org/"

      - name: 游닌 Install pnpm
        run: npm install -g pnpm@10.10.0

      - name: 游닌 Install tsx
        run: pnpm add -g tsx

      - name: 游닍 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 游댣 Build packages
        run: pnpm -r build

      - name: 游 Publish to NPMJS
        run: pnpm changeset publish --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
